### ISSUE TITLE
'ebpp_genes_sig' not found

### ISSUE THREAD

**Issue by andrewelamb** [Gibbsdavidl/ImmuneSubtypeClassifier#5]
Hi Dave, I'm using this commit: 30e6215

and getting this error:

calls <- ImmuneSubtypeClassifier::callEnsemble(input_matrix)

Error in geneMatch(X, geneids) : object 'ebpp_genes_sig' not found
Calls: <Anonymous> -> geneMatch
In addition: Warning messages:
1: In data("subtype_caller_model") :
  data set ‘subtype_caller_model’ not found
2: In data("ensemble_model") : data set ‘ensemble_model’ not found
3: In data(ebpp_gene) : data set ‘ebpp_gene’ not found
Execution halted

**Comment by Gibbsdavidl** [comment]
Well that's weird.

What sort of environment is this running in? Is it in a docker?

Do you think it's caused from not loading the library?
These are brought into the environment with data() calls...

**Comment by andrewelamb** [comment]
Loading the library fixed that, thanks!
